# -*- coding: utf-8 -*-
"""
OpenSCAD integration bridge.
Compiles OpenSCAD code to STL via the openscad CLI.
Also generates OpenSCAD code from GUI shapes.
"""

import subprocess
import tempfile
import os
import shutil
import math


class ScadBridge:
    def __init__(self, openscad_path: str = None):
        # Auto-detect openscad binary
        if openscad_path:
            self.openscad_path = openscad_path
        else:
            self.openscad_path = self._find_openscad()

    def _find_openscad(self) -> str:
        """Try to locate the OpenSCAD executable."""
        candidates = [
            "openscad",
            r"C:\Program Files\OpenSCAD\openscad.exe",
            r"C:\Program Files (x86)\OpenSCAD\openscad.exe",
            "/usr/bin/openscad",
            "/usr/local/bin/openscad",
            "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD",
        ]
        for c in candidates:
            if shutil.which(c) or os.path.isfile(c):
                return c
        return "openscad"  # Fallback, will fail gracefully

    def is_available(self) -> bool:
        """Check if OpenSCAD is installed and available."""
        try:
            result = subprocess.run(
                [self.openscad_path, "--version"],
                capture_output=True, timeout=5
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def compile_to_stl(self, scad_code: str) -> tuple[str | None, str]:
        """
        Compile OpenSCAD code to an STL file.
        Returns (stl_path, error_message). stl_path is None on error.
        """
        scad_file = None
        stl_file = None
        try:
            # Write SCAD code to temp file
            with tempfile.NamedTemporaryFile(
                suffix=".scad", delete=False, mode="w", encoding="utf-8"
            ) as f:
                f.write(scad_code)
                scad_file = f.name

            stl_file = scad_file.replace(".scad", ".stl")

            result = subprocess.run(
                [self.openscad_path, "-o", stl_file, scad_file],
                capture_output=True,
                timeout=60,
                text=True,
            )

            if result.returncode == 0 and os.path.exists(stl_file):
                return stl_file, ""
            else:
                error = result.stderr or result.stdout or "Unknown compile error"
                # Clean up the (empty/partial) STL file on error
                if stl_file and os.path.exists(stl_file):
                    try:
                        os.unlink(stl_file)
                    except OSError:
                        pass
                return None, error

        except FileNotFoundError:
            return None, "OpenSCAD not found. Please install OpenSCAD."
        except subprocess.TimeoutExpired:
            # Clean up partial STL on timeout
            if stl_file and os.path.exists(stl_file):
                try:
                    os.unlink(stl_file)
                except OSError:
                    pass
            return None, "OpenSCAD compile timed out (>60s)."
        except Exception as e:
            return None, str(e)
        finally:
            if scad_file and os.path.exists(scad_file):
                os.unlink(scad_file)

    def shape_to_scad(self, shape_type: str, params: dict) -> str:
        """Generate OpenSCAD code for a given shape type and parameters."""
        generators = {
            "box":        self._scad_box,
            "sphere":     self._scad_sphere,
            "cylinder":   self._scad_cylinder,
            "cone":       self._scad_cone,
            "torus":      self._scad_torus,
            "prism":      self._scad_prism,
            "pyramid":    self._scad_pyramid,
            "tube":       self._scad_tube,
            "ellipsoid":  self._scad_ellipsoid,
            "hemisphere": self._scad_hemisphere,
            "l_profile":  self._scad_l_profile,
            "t_profile":  self._scad_t_profile,
            "star":       self._scad_star,
            "polygon":    self._scad_polygon,
            "thread_cyl": self._scad_thread_cyl,
        }
        gen = generators.get(shape_type)
        if gen:
            return gen(params)
        return f"// Unknown shape type: {shape_type}\n"

    def scene_to_scad(self, objects: list) -> str:
        """Generate OpenSCAD code for a list of scene objects."""
        lines = ["// Generated by 3D Builder for 3D Printing\n"]
        for obj in objects:
            shape_code = self.shape_to_scad(obj["shape_type"], obj["params"])
            x, y, z = obj.get("pos_x", 0), obj.get("pos_y", 0), obj.get("pos_z", 0)
            rx, ry, rz = obj.get("rot_x", 0), obj.get("rot_y", 0), obj.get("rot_z", 0)
            lines.append(f"// {obj.get('name', 'Object')}")
            lines.append(f"translate([{x}, {y}, {z}])")
            lines.append(f"  rotate([{rx}, {ry}, {rz}])")
            lines.append(f"  {shape_code}")
        return "\n".join(lines)

    # ── SCAD generators ──────────────────────────────────────────────────────

    def _scad_box(self, p):
        return f"cube([{p['width']}, {p['depth']}, {p['height']}], center=true);"

    def _scad_sphere(self, p):
        return f"sphere(r={p['radius']}, $fn=64);"

    def _scad_cylinder(self, p):
        return f"cylinder(h={p['height']}, r={p['radius']}, center=true, $fn=64);"

    def _scad_cone(self, p):
        return (
            f"cylinder(h={p['height']}, r1={p['radius_bottom']}, "
            f"r2={p['radius_top']}, center=true, $fn=64);"
        )

    def _scad_torus(self, p):
        return (
            f"rotate_extrude($fn=64)\n"
            f"  translate([{p['radius_major']}, 0, 0])\n"
            f"  circle(r={p['radius_minor']}, $fn=32);"
        )

    def _scad_prism(self, p):
        return f"cylinder(h={p['height']}, r={p['radius']}, center=true, $fn={int(p['sides'])});"

    def _scad_pyramid(self, p):
        s = p['base_size'] / 2
        h = p['height']
        return (
            f"polyhedron(\n"
            f"  points=[[-{s},-{s},0],[{s},-{s},0],[{s},{s},0],[-{s},{s},0],[0,0,{h}]],\n"
            f"  faces=[[0,1,2,3],[0,1,4],[1,2,4],[2,3,4],[3,0,4]]\n"
            f");"
        )

    def _scad_tube(self, p):
        return (
            f"difference() {{\n"
            f"  cylinder(h={p['height']}, r={p['radius_outer']}, center=true, $fn=64);\n"
            f"  cylinder(h={p['height']}+0.1, r={p['radius_inner']}, center=true, $fn=64);\n"
            f"}}"
        )

    def _scad_ellipsoid(self, p):
        return (
            f"scale([{p['rx']}, {p['ry']}, {p['rz']}])\n"
            f"  sphere(r=1, $fn=64);"
        )

    def _scad_hemisphere(self, p):
        r = p['radius']
        return (
            f"difference() {{\n"
            f"  sphere(r={r}, $fn=64);\n"
            f"  translate([0, 0, -{r}])\n"
            f"    cube([{r*3}, {r*3}, {r*2}], center=true);\n"
            f"}}"
        )

    def _scad_l_profile(self, p):
        w, h, t, length = p['width'], p['height'], p['thickness'], p['length']
        return (
            f"linear_extrude(height={length})\n"
            f"  polygon(points=[[0,0],[{w},0],[{w},{t}],[{t},{t}],[{t},{h}],[0,{h}]]);"
        )

    def _scad_t_profile(self, p):
        w, h, t, length = p['width'], p['height'], p['thickness'], p['length']
        hw = w / 2
        ht = t / 2
        return (
            f"linear_extrude(height={length})\n"
            f"  polygon(points=[[-{hw},0],[{hw},0],[{hw},{t}],[{ht},{t}],"
            f"[{ht},{h}],[-{ht},{h}],[-{ht},{t}],[-{hw},{t}]]);"
        )

    def _scad_star(self, p):
        outer_r, inner_r = p['outer_r'], p['inner_r']
        points = int(p['points'])
        height = p['height']
        pts = []
        for i in range(points * 2):
            angle = math.pi * i / points - math.pi / 2
            r = outer_r if i % 2 == 0 else inner_r
            pts.append(f"[{r * math.cos(angle):.4f},{r * math.sin(angle):.4f}]")
        return (
            f"linear_extrude(height={height})\n"
            f"  polygon(points=[{','.join(pts)}]);"
        )

    def _scad_polygon(self, p):
        return f"cylinder(h={p['height']}, r={p['radius']}, center=true, $fn={int(p['sides'])});"

    def _scad_thread_cyl(self, p):
        r, h, pitch = p['radius'], p['height'], p['pitch']
        return (
            f"// Threaded cylinder (simplified)\n"
            f"cylinder(h={h}, r={r}, center=true, $fn=64);"
        )
